version: '3.8'

services:
  sqlite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlite3-db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/app
    restart: unless-stopped
